root: ./products

structure:
  readme: .gitbook_readme
  summary: .gitbook_summary

redirects:  
    memgraph/introduction: memgraph/v1.3.0/overview.md
    memgraph/quick-start: memgraph/v1.3.0/getting_started/getting-started.md
    #Tutorials
    memgraph/tutorials-overview: memgraph/v1.3.0/tutorials/tutorials.md
    memgraph/tutorials-overview/analyzing-TED-talks: memgraph/v1.3.0/tutorials/analyzing-TED-talks.md
    memgraph/tutorials-overview/backpacking-through-europe: memgraph/v1.3.0/tutorials/backpacking-through-europe.md
    memgraph/tutorials-overview/exploring-the-european-road-network: memgraph/v1.3.0/tutorials/exploring-the-european-road-network.md
    memgraph/tutorials-overview/football-transfers: memgraph/v1.3.0/tutorials/football-transfers.md
    memgraph/tutorials-overview/graphing-the-premier-league: memgraph/v1.3.0/tutorials/graphing-the-premier-league.md
    memgraph/tutorials-overview/marvel-universe: memgraph/v1.3.0/tutorials/marvel-universe.md
    memgraph/tutorials-overview/movie-recommendation: memgraph/v1.3.0/tutorials/movie-recommendation.md
    memgraph/tutorials-overview/understanding-music-with-modules: memgraph/v1.3.0/tutorials/understanding-music-with-modules.md
    memgraph/tutorials-overview/social-network-analysis: memgraph/v1.3.0/tutorials/social-network-analysis.md
    #How to guides
    memgraph/how-to-guides-overview: memgraph/v1.3.0/database_functionalities/database-functionalities.md
    memgraph/how-to-guides-overview/explain-profile: memgraph/v1.3.0/database_functionalities/profiling-queries.md
    memgraph/how-to-guides-overview/import-data: memgraph/v1.3.0/database_functionalities/import-data.md
    memgraph/how-to-guides-overview/query-memgraph-programmatically: memgraph/v1.3.0/getting_started/connecting_applications/connecting-applications.md
    memgraph/how-to-guides-overview/enforce-constraints: memgraph/v1.3.0/database_functionalities/constraints/constraints.md
    memgraph/how-to-guides-overview/load-query-modules: memgraph/v1.3.0/database_functionalities/query_modules/load-call-query-modules.md
    memgraph/how-to-guides-overview/call-query-module-procedures: memgraph/v1.3.0/database_functionalities/query_modules/load-call-query-modules.md
    memgraph/how-to-guides-overview/implement-query-modules: memgraph/v1.3.0/database_functionalities/query_modules/implement-query-modules.md
    memgraph/how-to-guides-overview/use-query-modules-provided-by-memgraph: memgraph/v1.3.0/database_functionalities/query_modules/built-in-query-modules.md
    memgraph/how-to-guides-overview/manage-user-privileges: memgraph/v1.3.0/database_functionalities/manage-user-privileges.md
    memgraph/how-to-guides-overview/manage-users-using-ldap: memgraph/v1.3.0/database_functionalities/manage-users-using-ldap.md
    memgraph/how-to-guides-overview/work-with-docker: memgraph/v1.3.0/database_functionalities/work-with-docker.md
    #Reference guide
    memgraph/reference-overview/configuration: memgraph/v1.3.0/reference_guide/configuration.md
    memgraph/reference-overview/reading-existing-data: memgraph/v1.3.0/cypher_manual/reading-existing-data.md
    memgraph/reference-overview/writing-new-data: memgraph/v1.3.0/cypher_manual/writing-new-data.md
    memgraph/reference-overview/reading-and-writing: memgraph/v1.3.0/cypher_manual/reading-and-writing.md
    memgraph/reference-overview/indexing: memgraph/v1.3.0/reference_guide/indexing.md
    memgraph/reference-overview/graph-algorithms: memgraph/v1.3.0/reference_guide/graph-algorithms.md
    memgraph/reference-overview/query-modules: memgraph/v1.3.0/reference_guide/query_modules/query-modules.md
    memgraph/reference-overview/query-modules/c-api: memgraph/v1.3.0/reference_guide/query_modules/c-api.md
    memgraph/reference-overview/query-modules/python-api: memgraph/v1.3.0/reference_guide/query_modules/python-api.md
    memgraph/reference-overview/networkx: memgraph/v1.3.0/reference_guide/networkx/networkx.md
    memgraph/reference-overview/networkx/graph-analyzer: memgraph/v1.3.0/reference_guide/networkx/graph_analyzer/graph_analyzer.md
    memgraph/reference-overview/networkx/wcc: memgraph/v1.3.0/reference_guide/networkx/wcc/wcc.md
    memgraph/reference-overview/networkx/nxalg: memgraph/v1.3.0/reference_guide/networkx/nxalg/nxalg.md
    memgraph/reference-overview/security: memgraph/v1.3.0/reference_guide/security.md
    memgraph/reference-overview/auth-module: memgraph/v1.3.0/reference_guide/auth-module.md
    memgraph/reference-overview/ldap-security: memgraph/v1.3.0/reference_guide/ldap-security.md
    memgraph/reference-overview/audit-log: memgraph/v1.3.0/reference_guide/audit-log.md
    memgraph/reference-overview/other-features: memgraph/v1.3.0/cypher_manual/other-features.md
    memgraph/reference-overview/differences: memgraph/v1.3.0/cypher_manual/differences.md
    #Cypher manual
    memgraph/open-cypher: memgraph/v1.3.0/cypher_manual/cypher-manual.md
    memgraph/open-cypher/functions: memgraph/v1.3.0/cypher_manual/functions.md
    memgraph/open-cypher/clauses: memgraph/v1.3.0/cypher_manual/clauses/clauses.md
    memgraph/open-cypher/clauses/create: memgraph/v1.3.0/cypher_manual/clauses/create.md
    memgraph/open-cypher/clauses/delete: memgraph/v1.3.0/cypher_manual/clauses/delete.md
    memgraph/open-cypher/clauses/match: memgraph/v1.3.0/cypher_manual/clauses/match.md
    memgraph/open-cypher/clauses/merge: memgraph/v1.3.0/cypher_manual/clauses/merge.md
    memgraph/open-cypher/clauses/optional-match: memgraph/v1.3.0/cypher_manual/clauses/optional-match.md
    memgraph/open-cypher/clauses/remove: memgraph/v1.3.0/cypher_manual/clauses/remove.md
    memgraph/open-cypher/clauses/return: memgraph/v1.3.0/cypher_manual/clauses/return.md
    memgraph/open-cypher/clauses/set: memgraph/v1.3.0/cypher_manual/clauses/set.md
    memgraph/open-cypher/clauses/union: memgraph/v1.3.0/cypher_manual/clauses/union.md
    memgraph/open-cypher/clauses/unwind: memgraph/v1.3.0/cypher_manual/clauses/unwind.md
    memgraph/open-cypher/clauses/where: memgraph/v1.3.0/cypher_manual/clauses/where.md
    memgraph/open-cypher/clauses/with: memgraph/v1.3.0/cypher_manual/clauses/with.md
    #Machine learning
    machine-learning/tensorflow-op: memgraph/v1.3.0/database_functionalities/tensorflow-setup.md
    machine-learning/tensorflow-op/tensorflow: memgraph/v1.3.0/database_functionalities/tensorflow-setup.md
    #Help
    memgraph/faq: memgraph/v1.3.0/getting_help/faq.md
    #Memgraph Lab
    memgraph-lab/style_script: lab/v1.2.0/style-script.md